configMapGenerator:
- files:
  - application.yml
  name: 82022176-configmap
  namespace: "82022176"  # 네임스페이스를 명시
resources:
- ../../base
- pvc.yaml
patchesStrategicMerge:
- deployment.yaml
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
images:
- name: cepgbaseacr.azurecr.io/82022176
  newTag: "202408090453"
